# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Git Vertag
      id: git_tag
        # You may pin to the exact commit or the version.
        # uses: kyoh86/git-vertag-action@dc7d9bed0695ed9e0f25c88cc845095ae1bf3606
      uses: kyoh86/git-vertag-action@v1
      with:
        # Which number to increment in the semantic versioning.
        # Set 'major', 'minor', 'patch' or 'get'.
        method: patch
        # If the new tag should be pushed, set "true".
        push: true # optional, default is false
   
