# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Git Vertag
      id: git_tag
        # You may pin to the exact commit or the version.
        # uses: kyoh86/git-vertag-action@dc7d9bed0695ed9e0f25c88cc845095ae1bf3606
      uses: kyoh86/git-vertag-action@v1
      with:
        # Which number to increment in the semantic versioning.
        # Set 'major', 'minor', 'patch' or 'get'.
        method: minor
        # If the new tag should be pushed, set "true".
        push: true # optional, default is false

    - name: Publish project
      run: dotnet publish ./Northwind.Demo.Server/Northwind.Demo.Server.csproj -c Release -o ./publish

    - name: Upload to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: ./publish/*
        target: /home/${{ secrets.EC2_USER }}/myapp/
        rm: true

    - name: SSH into EC2 and restart app
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
            export TMUX_TMPDIR=/tmp
            tmux kill-session -t northwind || true  
            tmux new-session -d -s northwind "cd /home/${{ secrets.EC2_USER }}/myapp/publish && ASPNETCORE_URLS=http://127.0.0.1:5000 dotnet Northwind.Demo.Server.dll"
    
